# image
image: Visual Studio 2015

# build platform
platform: x64

# clone directory
clone_folder: c:\hwloc

environment:
  prefix: c:\hwloc\hwloc-win64-build-1.11.7
  
build_script:
  - cd c:\hwloc
  - set PATH=%PATH%;C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
  - dir C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
  - ./configure --prefix=%prefix% --enable-static --host=x86_64-w64-mingw32
  - make
  - make install
  - make check

artifacts:
  - path: c:\hwloc
    name: project_data