# image
image: Visual Studio 2015

# build platform
platform: x64

# clone directory
clone_folder: c:\hwloc

environment:
  prefix: c:\hwloc\hwloc-win64-build-1.11.7
  
build_script:
  - cd c:\hwloc
  - set PATH=%PATH%;C:\msys64;C:\msys64\usr\bin;
  - bash build.sh

artifacts:
  - path: c:\hwloc
    name: project_data