# image
image: Visual Studio 2015

# build platform
platform: x64

# clone directory
clone_folder: c:\hwloc
  
build_script:
  - set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\;C:\msys64\usr\bin;C:\msys64;%PATH%
  - bash autogen.sh
  
artifacts:
  - path: c:\hwloc
    name: project_data