# image
image: Visual Studio 2015

# build platform
platform: x64

# clone directory
clone_folder: c:\hwloc

init:
  - cmd:

environment:
  matrix:
  - EXTRA_PATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\
    LAUNCH_BUILD: bash configure --enable-static --host=x86_64-w64-mingw32;mingw32-make;mingw32-make install;mingw32-make check
    LAUNCH_PATH: build\

install:
- cmd:
  
build_script:
  - mkdir build
  - set PATH=%EXTRA_PATH%;%PATH%
  - %LAUNCH_BUILD%
  - file %LAUNCH_PATH:\=/%*

artifacts:
  - path: c:\hwloc
    name: project_data