# image
image: Visual Studio 2015

# build platform
platform: x64

# clone directory
clone_folder: c:\hwloc

  
build_script:
  - cd c:\hwloc
  - mkdir build
  - cd build
  - winball=hwloc-win64-build-1.11.7
  - prefix=${PWD}/../${winball}
  - ../configure --prefix=$prefix --enable-static --host=x86_64-w64-mingw32
  - make
  - make install
  - make check

artifacts:
  - path: c:\hwloc
    name: project_data