# image
image: Visual Studio 2015

# build platform
platform: x64

# clone directory
clone_folder: c:\hwloc

environment:
  prefix: c:\hwloc\hwloc-win64-build-1.11.7
  
build_script:
  - cd c:\hwloc
  - set PATH=%PATH%;C:\msys64
  - dir C:\msys64
  - msys2 "pacman -S mingw-w64-i686-gcc; pacman -S mingw-w64-x86_64-gcc; pacman -S make"
  - msys2 "configure --prefix=%prefix% --enable-static --host=x86_64-w64-mingw32"
  - msys2 "make"
  - msys2 "make install"
  - msys2 "make check"

artifacts:
  - path: c:\hwloc
    name: project_data